### PR TITLE
Add placeholder component

### PR DESCRIPTION
**Pull request by isSerge**
image

Placeholder component can be enabled with the `REACT_APP_SHOW_PLACEHOLDER` env variable (currently enabled)

### CODE REVIEW

**Review by nazar-pc — COMMENTED** [review]
I'm not sure about the wording. It is not really being updated, more like on reconstruction or something like that. @stefanopepe any suggestions?

**Comment by stefanopepe** [comment]
@nazar-pc just an idea:
`Subspace Relayer is receiving an important update. The new version is not yet ready, join us on [Discord](https://discord.gg/subspace-network) to know when it is back!`

**Comment by nazar-pc** [comment]
The thing is it isn't right now, it is just suspended indefinitely.

**Comment by stefanopepe** [comment]
If this is the case, we just have to keep the expectations lower, something like:
`Subspace Relayer is not under active development right now. Join us on [Discord](https://discord.gg/subspace-network) to know when we are working on the new version!`

Ideally, we want to track the clicks on this link, building a basic signal on the demand.

**Review by nazar-pc — APPROVED** [review]

**Pull request merged**
